route: /apechain
protocol: evm
chainId: 33139
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.apechain.com
    priority: 1
  - url: https://apechain.drpc.org
    priority: 1
