route: /beam
protocol: evm
chainId: 4337
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://build.onbeam.com/rpc
    priority: 1
  - url: https://subnets.avax.network/beam/mainnet/rpc
    priority: 1
