route: /bitgert
protocol: evm
chainId: 32520
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc-bitgert.icecreamswap.com
    priority: 1
  - url: https://nodes.vefinetwork.org/bitgert
    priority: 1
  - url: https://flux-rpc.brisescan.com
    priority: 1
  - url: https://flux-rpc1.brisescan.com
    priority: 1
  - url: https://flux-rpc2.brisescan.com
    priority: 1
  - url: https://rpc-1.chainrpc.com
    priority: 1
  - url: https://rpc-2.chainrpc.com
    priority: 1
  - url: https://node1.serverrpc.com
    priority: 1
  - url: https://node2.serverrpc.com
    priority: 1
  - url: https://mainnet-rpc.brisescan.com
    priority: 1
  - url: https://chainrpc.com
    priority: 1
  - url: https://serverrpc.com
    priority: 1
