route: /bitlayer
protocol: evm
chainId: 200901
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.bitlayer.org
    priority: 1
  - url: https://rpc.ankr.com/bitlayer
    priority: 1
  - url: https://rpc.bitlayer-rpc.com
    priority: 1
  - url: https://rpc-bitlayer.rockx.com
    priority: 1
