route: /bitrock
protocol: evm
chainId: 7171
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://connect.bit-rock.io
    priority: 1
  - url: https://brockrpc.io
    priority: 1
