route: /blast
protocol: evm
chainId: 81457
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.blast.io
    priority: 1
  - url: https://blast.din.dev/rpc
    priority: 1
  - url: https://blastl2-mainnet.public.blastapi.io
    priority: 1
  - url: https://rpc.ankr.com/blast
    priority: 1
  - url: https://blast.gasswap.org
    priority: 1
  - url: https://blast-rpc.publicnode.com
    priority: 1
  - url: https://blast.drpc.org
    priority: 1
  - url: https://blast.gateway.tenderly.co
    priority: 1
  - url: https://endpoints.omniatech.io/v1/blast/mainnet/public
    priority: 1
  - url: https://rpc.owlracle.info/blast/70d38ce1826c4a60bb2a8e05a6c8b20f
    priority: 1
  - url: https://blast-public.nodies.app
    priority: 1
  - url: https://blast.therpc.io
    priority: 1
  - url: https://blast.rpc.grove.city/v1/01fdb492
    priority: 1
  - url: https://blast.blockpi.network/v1/rpc/public
    priority: 1
