route: /boba
protocol: evm
chainId: 288
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://mainnet.boba.network
    priority: 1
  - url: https://boba-ethereum.gateway.tenderly.co
    priority: 1
  - url: https://gateway.tenderly.co/public/boba-ethereum
    priority: 1
  - url: https://1rpc.io/boba/eth
    priority: 1
  - url: https://boba-eth.drpc.org
    priority: 1
  - url: https://boba.rpc.grove.city/v1/01fdb492
    priority: 1
  - url: https://replica.boba.network
    priority: 1
