route: /celo
protocol: evm
chainId: 42220
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://forno.celo.org
    priority: 1
  - url: https://rpc.ankr.com/celo
    priority: 1
  - url: https://celo-mainnet.gateway.tatum.io
    priority: 1
  - url: https://celo.drpc.org
    priority: 1
  - url: https://celo-json-rpc.stakely.io
    priority: 1
  - url: https://celo.api.onfinality.io/public
    priority: 1
