route: /cronos-zkevm
protocol: evm
chainId: 388
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://mainnet.zkevm.cronos.org
    priority: 1
  - url: https://cronos-zkevm.drpc.org
    priority: 1
