route: /cube
protocol: evm
chainId: 1818
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://http-mainnet.cube.network
    priority: 1
  - url: https://http-mainnet-sg.cube.network
    priority: 1
  - url: https://http-mainnet-us.cube.network
    priority: 1
