route: /dchain
protocol: evm
chainId: 2716446429837000
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://dchain-2716446429837000-1.jsonrpc.sagarpc.io
    priority: 1
