route: /dogechain
protocol: evm
chainId: 2000
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.dogechain.dog
    priority: 1
  - url: https://rpc-us.dogechain.dog
    priority: 1
  - url: https://rpc-sg.dogechain.dog
    priority: 1
  - url: https://rpc.dogechain.dog
    priority: 1
  - url: https://rpc01-sg.dogechain.dog
    priority: 1
  - url: https://rpc02-sg.dogechain.dog
    priority: 1
  - url: https://rpc03-sg.dogechain.dog
    priority: 1
  - url: https://doge-mainnet.gateway.tatum.io
    priority: 1
  - url: https://rpc.ankr.com/dogechain
    priority: 1
