route: /elastos
protocol: evm
chainId: 20
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://api.elastos.io/esc
    priority: 1
  - url: https://api.trinity-tech.io/esc
    priority: 1
  - url: https://api2.elastos.io/esc
    priority: 1
  - url: https://api2.elastos.net/esc
    priority: 1
  - url: https://api2.elastos.io/eth
    priority: 1
  - url: https://api2.elastos.net/eth
    priority: 1
  - url: https://rpc.glidefinance.io
    priority: 1
  - url: https://api.elastos.io/eth
    priority: 1
