route: /enuls
protocol: evm
chainId: 119
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://evmapi.nuls.io
    priority: 1
  - url: https://evmapi2.nuls.io
    priority: 1
