route: /ethereum
protocol: evm
chainId: 1
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://eth.llamarpc.com
    priority: 1
  - url: https://go.getblock.io/aefd01aa907c4805ba3c00a9e5b48c6b
    priority: 1
  - url: https://eth-mainnet.nodereal.io/v1/1659dfb40aa24bbb8153a677b98064d7
    priority: 1
  - url: https://ethereum-rpc.publicnode.com
    priority: 1
  - url: https://1rpc.io/eth
    priority: 1
  - url: https://rpc.builder0x69.io
    priority: 1
  - url: https://rpc.mevblocker.io
    priority: 1
  - url: https://rpc.flashbots.net
    priority: 1
  - url: https://virginia.rpc.blxrbdn.com
    priority: 1
  - url: https://uk.rpc.blxrbdn.com
    priority: 1
  - url: https://singapore.rpc.blxrbdn.com
    priority: 1
  - url: https://eth.rpc.blxrbdn.com
    priority: 1
  - url: https://cloudflare-eth.com
    priority: 1
  - url: https://eth-mainnet.public.blastapi.io
    priority: 1
  - url: https://api.securerpc.com/v1
    priority: 1
  - url: https://openapi.bitstack.com/v1/wNFxbiJyQsSeLrX8RRCHi7NpRxrlErZk/DjShIqLishPCTB9HiMkPHXjUM9CNM9Na/ETH/mainnet
    priority: 1
  - url: https://ethereum-public.nodies.app
    priority: 1
  - url: https://eth-mainnet-public.unifra.io
    priority: 1
  - url: https://ethereum.public.blockpi.network/v1/rpc/public
    priority: 1
  - url: https://rpc.payload.de
    priority: 1
  - url: https://api.zmok.io/mainnet/oaen6dy8ff6hju9k
    priority: 1
  - url: https://eth-mainnet.g.alchemy.com/v2/demo
    priority: 1
  - url: https://core.gashawk.io/rpc
    priority: 1
  - url: https://mainnet.eth.cloud.ava.do
    priority: 1
  - url: https://ethereumnodelight.app.runonflux.io
    priority: 1
  - url: https://eth-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf
    priority: 1
  - url: https://main-light.eth.linkpool.io
    priority: 1
  - url: https://rpc.eth.gateway.fm
    priority: 1
  - url: https://rpc.chain49.com/ethereum?api_key=14d1a8b86d8a4b4797938332394203dc
    priority: 1
  - url: https://eth.meowrpc.com
    priority: 1
  - url: https://eth.drpc.org
    priority: 1
  - url: https://mainnet.gateway.tenderly.co
    priority: 1
  - url: https://virtual.mainnet.rpc.tenderly.co/7355b215-ef17-4e3e-8f64-d494284ef18a
    priority: 1
  - url: https://virtual.mainnet.rpc.tenderly.co/5804dcf7-70e6-4988-b2b0-3672193e0c91
    priority: 1
  - url: https://gateway.tenderly.co/public/mainnet
    priority: 1
  - url: https://api.zan.top/eth-mainnet
    priority: 1
  - url: https://eth-mainnet.diamondswap.org/rpc
    priority: 1
  - url: https://rpc.notadegen.com/eth
    priority: 1
  - url: https://eth.merkle.io
    priority: 1
  - url: https://rpc.lokibuilder.xyz/wallet
    priority: 1
  - url: https://services.tokenview.io/vipapi/nodeservice/eth?apikey=qVHq2o6jpaakcw3lRstl
    priority: 1
  - url: https://eth.nodeconnect.org
    priority: 1
  - url: https://api.stateless.solutions/ethereum/v1/demo
    priority: 1
  - url: https://rpc.polysplit.cloud/v1/chain/1
    priority: 1
  - url: https://public.stackup.sh/api/v1/node/ethereum-mainnet
    priority: 1
  - url: https://ethereum-mainnet.gateway.tatum.io
    priority: 1
  - url: https://public-eth.nownodes.io
    priority: 1
  - url: https://rpc.nodifi.ai/api/rpc/free
    priority: 1
  - url: https://ethereum.rpc.subquery.network/public
    priority: 1
  - url: https://rpc.graffiti.farm
    priority: 1
  - url: https://rpc.public.curie.radiumblock.co/http/ethereum
    priority: 1
  - url: https://eth-mainnet.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f
    priority: 1
  - url: https://rpc.public.curie.radiumblock.co/ws/ethereum
    priority: 1
  - url: https://eth.blockrazor.xyz
    priority: 1
  - url: https://endpoints.omniatech.io/v1/eth/mainnet/public
    priority: 1
  - url: https://eth1.lava.build
    priority: 1
  - url: https://0xrpc.io/eth
    priority: 1
  - url: https://rpc.owlracle.info/eth/70d38ce1826c4a60bb2a8e05a6c8b20f
    priority: 1
  - url: https://ethereum.therpc.io
    priority: 1
  - url: https://eth.api.onfinality.io/public
    priority: 1
  - url: https://ethereum-json-rpc.stakely.io
    priority: 1
  - url: https://rpc.poolz.finance/eth
    priority: 1
  - url: https://eth.rpc.grove.city/v1/01fdb492
    priority: 1
  - url: https://api.mycryptoapi.com/eth
    priority: 1
  - url: https://rpc.blocknative.com/boost
    priority: 1
  - url: https://rpc.flashbots.net/fast
    priority: 1
  - url: https://rpc.mevblocker.io/fast
    priority: 1
  - url: https://rpc.mevblocker.io/noreverts
    priority: 1
  - url: https://rpc.mevblocker.io/fullprivacy
    priority: 1
