route: /evmos
protocol: evm
chainId: 9001
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://evmos.lava.build
    priority: 1
  - url: https://evmos-mainnet.public.blastapi.io
    priority: 1
  - url: https://evmos-evm-rpc.publicnode.com
    priority: 1
  - url: https://jsonrpc-evmos.goldenratiostaking.net
    priority: 1
  - url: https://evmos.api.onfinality.io/public
    priority: 1
  - url: https://evmos-jsonrpc.cyphercore.io
    priority: 1
  - url: https://evmos.drpc.org
    priority: 1
  - url: https://eth.bd.evmos.org:8545
    priority: 1
  - url: https://evmos-json-rpc.stakely.io
    priority: 1
  - url: https://jsonrpc-evmos-ia.cosmosia.notional.ventures
    priority: 1
  - url: https://json-rpc.evmos.blockhunters.org
    priority: 1
  - url: https://evmos-json-rpc.agoranodes.com
    priority: 1
  - url: https://evmos-json.antrixy.org
    priority: 1
  - url: https://jsonrpc.evmos.nodestake.top
    priority: 1
  - url: https://evmos-jsonrpc.alkadeta.com
    priority: 1
  - url: https://evmos-json.qubelabs.io
    priority: 1
  - url: https://evmos-rpc.theamsolutions.info
    priority: 1
  - url: https://evmos-api.theamsolutions.info
    priority: 1
  - url: https://evmos-jsonrpc.theamsolutions.info
    priority: 1
  - url: https://evm-rpc-evmos.hoodrun.io
    priority: 1
  - url: https://evmos-json-rpc.0base.dev
    priority: 1
  - url: https://json-rpc.evmos.tcnetwork.io
    priority: 1
  - url: https://rpc-evm.evmos.dragonstake.io
    priority: 1
  - url: https://evmosevm.rpc.stakin-nodes.com
    priority: 1
  - url: https://evmos-jsonrpc.stake-town.com
    priority: 1
  - url: https://json-rpc-evmos.mainnet.validatrium.club
    priority: 1
  - url: https://rpc-evmos.imperator.co
    priority: 1
  - url: https://evm-rpc.evmos.silentvalidator.com
    priority: 1
  - url: https://alphab.ai/rpc/eth/evmos
    priority: 1
  - url: https://evmos-jsonrpc.kalia.network
    priority: 1
  - url: https://jsonrpc-evmos.mzonder.com
    priority: 1
  - url: https://evmos.rpc.grove.city/v1/01fdb492
    priority: 1
