route: /fuse
protocol: evm
chainId: 122
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.fuse.io
    priority: 1
  - url: https://fuse-public.nodies.app
    priority: 1
  - url: https://fuse-mainnet.chainstacklabs.com
    priority: 1
  - url: https://fuse.api.onfinality.io/public
    priority: 1
  - url: https://fuse.liquify.com
    priority: 1
  - url: https://fuse.drpc.org
    priority: 1
  - url: https://rpc.owlracle.info/fuse/70d38ce1826c4a60bb2a8e05a6c8b20f
    priority: 1
  - url: https://fuse.rpc.grove.city/v1/01fdb492
    priority: 1
