route: /goat
protocol: evm
chainId: 2345
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.goat.network
    priority: 1
  - url: https://goat-mainnet-alpha.drpc.org
    priority: 1
  - url: https://rpc.ankr.com/goat_mainnet
    priority: 1
