route: /heco
protocol: evm
chainId: 128
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://http-mainnet.hecochain.com
    priority: 1
  - url: https://http-mainnet-node.huobichain.com
    priority: 1
  - url: https://hecoapi.terminet.io/rpc
    priority: 1
  - url: https://heco.drpc.org
    priority: 1
