route: /hemi
protocol: evm
chainId: 43111
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://hemi.drpc.org
    priority: 1
  - url: https://rpc.hemi.network/rpc
    priority: 1
