route: /immutable-zkevm
protocol: evm
chainId: 13371
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.immutable.com
    priority: 1
  - url: https://immutable-zkevm.drpc.org
    priority: 1
  - url: https://immutable-zkevm.drpc.org
    priority: 1
  - url: https://immutable.gateway.tenderly.co
    priority: 1
