route: /ink
protocol: evm
chainId: 57073
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc-gel.inkonchain.com
    priority: 1
  - url: https://rpc-qnd.inkonchain.com
    priority: 1
  - url: https://ink.drpc.org
    priority: 1
  - url: https://ink-public.nodies.app
    priority: 1
  - url: https://ink.rpc.grove.city/v1/01fdb492
    priority: 1
