route: /jbc
protocol: evm
chainId: 8899
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc-l1.jibchain.net
    priority: 1
  - url: https://rpc-l1.inan.in.th
    priority: 1
  - url: https://rpc-l1.jbc.xpool.pw
    priority: 1
  - url: https://rpc2-l1.jbc.xpool.pw
    priority: 1
