route: /lisk
protocol: evm
chainId: 1135
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.api.lisk.com
    priority: 1
  - url: https://lisk.drpc.org
    priority: 1
  - url: https://lisk.gateway.tenderly.co
    priority: 1
