route: /mantle
protocol: evm
chainId: 5000
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.mantle.xyz
    priority: 1
  - url: https://mantle-mainnet.public.blastapi.io
    priority: 1
  - url: https://mantle-public.nodies.app
    priority: 1
  - url: https://mantle-rpc.publicnode.com
    priority: 1
  - url: https://mantle.drpc.org
    priority: 1
  - url: https://1rpc.io/mantle
    priority: 1
  - url: https://mantle.api.onfinality.io/public
    priority: 1
  - url: https://api.zan.top/mantle-mainnet
    priority: 1
  - url: https://endpoints.omniatech.io/v1/mantle/mainnet/public
    priority: 1
  - url: https://rpc.owlracle.info/mantle/70d38ce1826c4a60bb2a8e05a6c8b20f
    priority: 1
  - url: https://mantle.therpc.io
    priority: 1
  - url: https://mantle.rpc.grove.city/v1/01fdb492
    priority: 1
