route: /matchain
protocol: evm
chainId: 698
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.matchain.io
    priority: 1
  - url: https://rpc.ankr.com/matchain_mainnet
    priority: 1
