route: /metis
protocol: evm
chainId: 1088
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://andromeda.metis.io/?owner=1088
    priority: 1
  - url: https://metis-mainnet.public.blastapi.io
    priority: 1
  - url: https://metis.api.onfinality.io/public
    priority: 1
  - url: https://metis-public.nodies.app
    priority: 1
  - url: https://metis.drpc.org
    priority: 1
  - url: https://metis-andromeda.rpc.thirdweb.com
    priority: 1
  - url: https://metis-andromeda.gateway.tenderly.co
    priority: 1
  - url: https://api.blockeden.xyz/metis/67nCBdZQSH9z3YqDDjdm
    priority: 1
  - url: https://metis.rpc.hypersync.xyz
    priority: 1
  - url: https://metis-rpc.publicnode.com
    priority: 1
