route: /mode
protocol: evm
chainId: 34443
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://mainnet.mode.network
    priority: 1
  - url: https://1rpc.io/mode
    priority: 1
  - url: https://mode.drpc.org
    priority: 1
  - url: https://mode.gateway.tenderly.co
    priority: 1
