route: /moonbeam
protocol: evm
chainId: 1284
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.api.moonbeam.network
    priority: 1
  - url: https://moonbeam.api.onfinality.io/public
    priority: 1
  - url: https://moonbeam.unitedbloc.com
    priority: 1
  - url: https://1rpc.io/glmr
    priority: 1
  - url: https://moonbeam-rpc.dwellir.com
    priority: 1
  - url: https://moonbeam.drpc.org
    priority: 1
  - url: https://moonbeam.therpc.io
    priority: 1
  - url: https://moonbeam-rpc.publicnode.com
    priority: 1
  - url: https://endpoints.omniatech.io/v1/moonbeam/mainnet/public
    priority: 1
  - url: https://moonbeam.public.curie.radiumblock.co/ws
    priority: 1
  - url: https://moonbeam.drpc.org
    priority: 1
  - url: https://rpc.poolz.finance/moonbeam
    priority: 1
  - url: https://node.histori.xyz/moonbeam-mainnet/8ry9f6t9dct1se2hlagxnd9n2a
    priority: 1
  - url: https://moonbeam.rpc.grove.city/v1/01fdb492
    priority: 1
  - url: https://moonbeam.public.blastapi.io
    priority: 1
