route: /neon
protocol: evm
chainId: 245022934
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://neon-proxy-mainnet.solana.p2p.org
    priority: 1
  - url: https://neon-mainnet.everstake.one
    priority: 1
  - url: https://neon-evm.drpc.org
    priority: 1
