route: /oasys
protocol: evm
chainId: 248
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.mainnet.oasys.games
    priority: 1
  - url: https://oasys.blockpi.network/v1/rpc/public
    priority: 1
  - url: https://oasys.rpc.grove.city/v1/01fdb492
    priority: 1
