route: /okexchain
protocol: evm
chainId: 66
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://exchainrpc.okex.org
    priority: 1
  - url: https://oktc-mainnet.public.blastapi.io
    priority: 1
  - url: https://okt-chain.api.onfinality.io/public
    priority: 1
  - url: https://1rpc.io/oktc
    priority: 1
  - url: https://oktc.drpc.org
    priority: 1
  - url: https://okc-mainnet.gateway.pokt.network/v1/lb/6275309bea1b320039c893ff
    priority: 1
