route: /omax
protocol: evm
chainId: 311
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://mainapi.omaxray.com
    priority: 1
  - url: https://mainapi.omaxscan.com
    priority: 1
