route: /op_bnb
protocol: evm
chainId: 204
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://opbnb-mainnet-rpc.bnbchain.org
    priority: 1
  - url: https://opbnb.drpc.org
    priority: 1
  - url: https://opbnb-rpc.publicnode.com
    priority: 1
  - url: https://1rpc.io/opbnb
    priority: 1
  - url: https://opbnb-mainnet.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f
    priority: 1
  - url: https://opbnb.therpc.io
    priority: 1
  - url: https://opbnb.rpc.grove.city/v1/01fdb492
    priority: 1
  - url: https://opbnb-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3
    priority: 1
  - url: https://opbnb-mainnet.nodereal.io/v1/e9a36765eb8a40b9bd12e680a1fd2bc5
    priority: 1
