route: /peaq
protocol: evm
chainId: 3338
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://quicknode1.peaq.xyz
    priority: 1
  - url: https://quicknode2.peaq.xyz
    priority: 1
  - url: https://quicknode3.peaq.xyz
    priority: 1
