route: /ronin
protocol: evm
chainId: 2020
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://ronin.drpc.org
    priority: 1
  - url: https://ronin-mainnet.gateway.tatum.io
    priority: 1
  - url: https://api.roninchain.com/rpc
    priority: 1
  - url: https://api-gateway.skymavis.com/rpc?apikey=9aqYLBbxSC6LROynQJBvKkEIsioqwHmr
    priority: 1
  - url: https://ronin.lgns.net/rpc
    priority: 1
