route: /sapphire
protocol: evm
chainId: 23294
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://sapphire.oasis.io
    priority: 1
  - url: https://1rpc.io/oasis/sapphire
    priority: 1
