route: /scroll
protocol: evm
chainId: 534352
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.scroll.io
    priority: 1
  - url: https://rpc-scroll.icecreamswap.com
    priority: 1
  - url: https://scroll-mainnet.public.blastapi.io
    priority: 1
  - url: https://scroll-mainnet-public.unifra.io
    priority: 1
  - url: https://1rpc.io/scroll
    priority: 1
  - url: https://scroll.drpc.org
    priority: 1
  - url: https://scroll-mainnet.rpc.grove.city/v1/a7a7c8e2
    priority: 1
  - url: https://scroll.api.onfinality.io/public
    priority: 1
  - url: https://scroll-public.nodies.app
    priority: 1
  - url: https://endpoints.omniatech.io/v1/scroll/mainnet/public
    priority: 1
  - url: https://rpc.ankr.com/scroll
    priority: 1
  - url: https://scroll.therpc.io
    priority: 1
  - url: https://scroll.rpc.grove.city/v1/01fdb492
    priority: 1
  - url: https://scroll-mainnet.chainstacklabs.com
    priority: 1
  - url: https://scroll-rpc.publicnode.com
    priority: 1
