route: /sei
protocol: evm
chainId: 1329
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://evm-rpc.sei-apis.com
    priority: 1
  - url: https://sei.drpc.org
    priority: 1
  - url: https://sei-evm-rpc.stakeme.pro
    priority: 1
  - url: https://sei-public.nodies.app
    priority: 1
  - url: https://sei.therpc.io
    priority: 1
  - url: https://sei.rpc.grove.city/v1/01fdb492
    priority: 1
