route: /somnia
protocol: evm
chainId: 5031
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://api.infra.mainnet.somnia.network
    priority: 1
  - url: https://somnia-json-rpc.stakely.io
    priority: 1
