route: /taiko
protocol: evm
chainId: 167000
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.taiko.xyz
    priority: 1
  - url: https://rpc.ankr.com/taiko
    priority: 1
  - url: https://rpc.taiko.tools
    priority: 1
  - url: https://taiko-mainnet.4everland.org/v1/37fa9972c1b1cd5fab542c7bdd4cde2f
    priority: 1
  - url: https://taiko.drpc.org
    priority: 1
  - url: https://taiko-mainnet.rpc.porters.xyz/taiko-public
    priority: 1
  - url: https://taiko-mainnet.gateway.tenderly.co
    priority: 1
  - url: https://taiko-json-rpc.stakely.io
    priority: 1
  - url: https://taiko.therpc.io
    priority: 1
  - url: https://taiko.rpc.grove.city/v1/01fdb492
    priority: 1
  - url: https://rpc.mainnet.taiko.xyz
    priority: 1
  - url: https://taiko-rpc.publicnode.com
    priority: 1
