route: /telos
protocol: evm
chainId: 40
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.telos.net
    priority: 1
  - url: https://1rpc.io/telos/evm
    priority: 1
  - url: https://telos.drpc.org
    priority: 1
  - url: https://rpc.ankr.com/telos
    priority: 1
  - url: https://rpc.poolz.finance/telos
    priority: 1
