route: /titan
protocol: evm
chainId: 18888
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://titan-json-rpc.titanlab.io
    priority: 1
  - url: https://titan-json-rpc-tokyo.titanlab.io
    priority: 1
  - url: https://titan-json-rpc-seoul.titanlab.io
    priority: 1
  - url: https://titan-json-rpc-hongkong.titanlab.io
    priority: 1
