route: /velas
protocol: evm
chainId: 106
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://evmexplorer.velas.com/rpc
    priority: 1
  - url: https://velas-mainnet.rpcfast.com?api_key=xbhWBI1Wkguk8SNMu1bvvLurPGLXmgwYeC4S6g2H7WdwFigZSmPWVZRxrskEQwIf
    priority: 1
  - url: https://explorer.velas.com/rpc
    priority: 1
