route: /wanchain
protocol: evm
chainId: 888
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://gwan-ssl.wandevs.org:56891
    priority: 1
  - url: https://gwan2-ssl.wandevs.org
    priority: 1
