route: /xphere
protocol: evm
chainId: 20250217
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://rpc.ankr.com/xphere_mainnet
    priority: 1
  - url: https://en-bkk.x-phere.com
    priority: 1
