route: /zetachain
protocol: evm
chainId: 7000
timeoutMs: 1500
gas:
  externalUrl: ""
  minPriorityGwei: 2
  ttlSeconds: 10
nodes:
  - url: https://zetachain-evm.blockpi.network/v1/rpc/public
    priority: 1
  - url: https://zetachain-mainnet.g.allthatnode.com/archive/evm
    priority: 1
  - url: https://zeta-chain.drpc.org
    priority: 1
  - url: https://zetachain-mainnet.public.blastapi.io
    priority: 1
  - url: https://7000.rpc.thirdweb.com
    priority: 1
  - url: https://zetachain-mainnet-evm.reliableninjas.com
    priority: 1
